### ISSUE TITLE
Please make tags and releases for this addon

### ISSUE THREAD

**Issue by AmsTaFFix** [ascott18/LibSpellRange-1.0#8]
It will be more convenient to make proper tagging and releases, so everybody could just download proper current stable version.

**Comment by AmsTaFFix** [comment]
@ascott18

**Comment by ascott18** [comment]
Can you help me understand the motivation and reasons behind this request?

Specifically - what's the need to install this library as a standalone addon?

**Comment by AmsTaFFix** [comment]
Main reason that master most of the time is unstable and do not ready to use, and repositories always have releases, where you can download latest stable version (what I did, and received old version :) ). 

Maybe I do not know the flow of working with such libraries in WoW and it is more convenient just to place a submodule in git repo and automatically update...

**Comment by ascott18** [comment]
> most of the time is unstable and do not ready to use

If you've found a functionality issue, please open a bug report and describe the problem that you've found.

Addon packaging works off the default branch of a repository, meaning what's in master is what's being packaged with each new build and release of TellMeWhen, WeakAuras, and other addons. This is true for virtually every addon library in existence.

Nobody makes or downloads nolib variants of addons anymore, so there's really no reason to be spending the effort you're asking for. If you're building an addon using LibSpellRange (which is what I've gathered from your mentions of submodules), just install the alpha versions locally and configure that as the channel in your addon updater.
